plugins {
    id "com.android.application"
}

ext {
    releaseDate = "2026-08-25"
}

android {
    namespace "dk.nenolink.learnportuguese2"
    compileSdk 35

    defaultConfig {
        applicationId "dk.nenolink.learnportuguese2"
        minSdk 23
        targetSdk 35
        versionCode 13
        versionName "0.2.1"
        resValue "string", "release_date", releaseDate
        resValue "string", "nenolink_url", "https://www.nenolink.dk"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

}

tasks.register("copyDebugApkForManualTesting") {
    dependsOn("packageDebug")
    doLast {
        copy {
            from(layout.buildDirectory.file("outputs/apk/debug/app-debug.apk"))
            into(layout.buildDirectory.dir("outputs/apk/debug"))
            rename { "LearnPortuguese2Test.apk" }
        }
    }
}

tasks.configureEach { task ->
    if (task.name == "assembleDebug") {
        task.finalizedBy("copyDebugApkForManualTesting")
    }
}
